eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8861/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true