configurtion:
  projectName: catalog-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8861/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true
spring:
  sleuth: 
    sampler:
      percentage: 0.5
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/catalog
    username: root
    password: Raja@123
  profiles:
    active:
    - test
  application:
    name: catalog-service
server:
  port: 0
---
spring:
  profiles: test
server:
  port: 0
---
spring:
  profiles: test1
server:
  port: 8088