configurtion:
  projectName: catalog-client
server:
  port: 8090
spring:
  sleuth: 
    sampler:
      percentage: 0.5
  application:
    name: catalog-client
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  kafka: 
    consumer: 
      group-id: group-1
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8861/eureka}